# general blog settings
blog-title: "Blog of Complaining"
time-zone: "Europe/Berlin"
blog-language: "en"

# rendering properties
posts-per-page: 4
max-posts: null
min-date: 2000-01-01T00:00:00+01:00

# rendering flags
render-post-separators: true
render-post-metadata: true
render-post-toc: true
render-post-content: true
